# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

resources:
  containers:
  - container: builder
    image: tachang/openmiko:latest


pool:
  vmImage: 'ubuntu-16.04'

trigger:
- master

container: builder

steps:
- script: |
    cd /openmiko/build/buildroot-2016.02/
    echo "Starting make"
    make
