# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
# Use a package of configuration called an orb.

# Orchestrate or schedule a set of jobs
workflows:
  # Name the workflow "welcome"
  buildImage:
    jobs:
      build:
        environment:
          IMAGE_NAME: openmiko/openmiko
        docker:
          - image: circleci/buildpack-deps:stretch
        steps:
          - checkout
          - setup_remote_docker
          - run:
              name: Build Docker image
              command: docker build -t $IMAGE_NAME:latest .
    workflows:
      version: 2
      build-master:
        jobs:
          - build:
              filters:
                branches:
                  only: circleci-project-setup